# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NeumorABTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # add the Firebase pod for Google Analytics
  #source "https://cpdc-eap.googlesource.com/spec.git"
  source "https://github.com/CocoaPods/Specs.git"
  pod 'FirebaseABTesting'

  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for NeumorABTest

  target 'NeumorABTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NeumorABTestUITests' do
    # Pods for testing
  end

end
